# 🚌 BusBuddy Dependabot Configuration
# Automated dependency updates for NuGet packages
# Reference: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # NuGet package updates for the main solution
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10

    # Review and merge settings
    reviewers:
      - "project-maintainer"
    assignees:
      - "project-maintainer"
    labels:
      - "dependencies"
      - "nuget"

    # Commit message preferences
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

    # Group related updates together
    groups:
      syncfusion:
        patterns:
          - "Syncfusion.*"
        update-types:
          - "minor"
          - "patch"

      microsoft-extensions:
        patterns:
          - "Microsoft.Extensions.*"
        update-types:
          - "minor"
          - "patch"

      entity-framework:
        patterns:
          - "Microsoft.EntityFrameworkCore.*"
        update-types:
          - "minor"
          - "patch"

      serilog:
        patterns:
          - "Serilog.*"
        update-types:
          - "minor"
          - "patch"

      testing:
        patterns:
          - "NUnit*"
          - "Moq*"
          - "FluentAssertions*"
          - "Coverlet.*"
          - "Microsoft.NET.Test.Sdk"
        update-types:
          - "minor"
          - "patch"

      google-apis:
        patterns:
          - "Google.*"
        update-types:
          - "minor"
          - "patch"

    # Ignore specific packages that require manual updates
    ignore:
      - dependency-name: "Syncfusion.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.EntityFrameworkCore.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Extensions.*"
        update-types: ["version-update:semver-major"]

    # Allow specific versions to be updated
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
        update-types: ["security"]

  # GitHub Actions workflow updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # NPM/Node.js dependencies (if package.json exists)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
