#
# Module manifest for module 'BusBuddy-GitWorkflow'
#
# Generated by: BusBuddy Development Team
#
# Generated on: 8/22/2025
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'BusBuddy-GitWorkflow.psm1'

    # Version number of this module.
    ModuleVersion = '1.0.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Core')

    # ID used to uniquely identify this module
    GUID = '8a1b2c3d-4e5f-6789-abcd-ef0123456789'

    # Author of this module
    Author = 'BusBuddy Development Team'

    # Company or vendor of this module
    CompanyName = 'BusBuddy Project'

    # Copyright statement for this module
    Copyright = '(c) BusBuddy Development Team. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'Microsoft-compliant Git workflow automation with integrated security scanning and fetchability index integration for Grok-4 AI analysis. Provides secure commit and push operations with mandatory secret detection and automated repository structure updates.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '7.5'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'Update-BusBuddyFetchabilityIndex',
        'Invoke-BusBuddyCommit',
        'Invoke-BusBuddyPush',
        'Invoke-BusBuddyCommitAndPush',
        'Invoke-BusBuddySecurityScan',
        'Invoke-BusBuddySecureCommit'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    FileList = @(
        'BusBuddy-GitWorkflow.psm1',
        'BusBuddy-GitWorkflow.psd1'
    )

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('Git', 'Workflow', 'Automation', 'Security', 'SecretDetection', 'BusBuddy', 'Grok-4', 'AI', 'Microsoft-Compliant')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/Bigessfour/BusBuddy-3/blob/master/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Bigessfour/BusBuddy-3'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = @'
Version 1.0.0 (2025-08-23)
==========================

Enhanced release with integrated security scanning capabilities.

Features:
- Microsoft PowerShell Standards compliant implementation
- Automated fetchability index integration for Grok-4 AI analysis
- Comprehensive Git workflow functions (commit, push, combined operations)
- **NEW: Mandatory security scanning to prevent secret exposure**
- **NEW: Enhanced secure commit workflow with pre-commit validation**
- Structured error handling and informational output
- Support for WhatIf and Verbose parameters
- Pre-push validation and safety checks

Security Functions:
- Invoke-BusBuddySecurityScan: Comprehensive security scan for secrets and API keys
- Invoke-BusBuddySecureCommit: Enhanced commit with mandatory security validation

Core Functions:
- Update-BusBuddyFetchabilityIndex: Updates repository structure index
- Invoke-BusBuddyCommit: Commits with fetchability index automation
- Invoke-BusBuddyPush: Pushes with pre-push validation
- Invoke-BusBuddyCommitAndPush: Complete workflow automation

Security Protection:
- Scans for hardcoded API keys (xAI, OpenAI, Azure, GitHub)
- Detects unsafe environment variable usage
- Checks for exposed secrets in filenames
- Optional Git history scanning for leaked credentials
- Blocks commits when critical security issues are found

Requirements:
- PowerShell 7.5+
- Git installed and configured
- BusBuddy project structure with generate-fetchability-index.ps1

Documentation:
- All functions include comprehensive help documentation
- Microsoft PowerShell documentation standards followed
- Examples provided for each function
- Security best practices integration

For more information, visit: https://github.com/Bigessfour/BusBuddy-3
'@

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
