#
# Module manifest for BusBuddy-Advanced
# Generated by: PowerShell 7.5.2 Profile Generator
# Generated on: 8/21/2025
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'BusBuddy-Advanced.psm1'

    # Version number of this module.
    ModuleVersion = '3.0.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Core', 'Desktop')

    # ID used to uniquely identify this module
    GUID = 'a7c5f8e2-4d6b-4c9e-8a3b-1f7e9d2c5b4a'

    # Author of this module
    Author = 'BusBuddy Development Team'

    # Company or vendor of this module
    CompanyName = 'BusBuddy Transportation Management'

    # Copyright statement for this module
    Copyright = '(c) 2025 BusBuddy. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'Advanced PowerShell 7.5.2 functions for BusBuddy development with hyperthreading support, parallel processing, and state-of-the-art PowerShell features.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '7.5'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @(
        @{ModuleName = 'PSScriptAnalyzer'; ModuleVersion = '1.0.0'},
        @{ModuleName = 'PSReadLine'; ModuleVersion = '2.0.0'}
    )

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'Invoke-BusBuddyParallel',
        'Invoke-BusBuddyFileProcessor', 
        'Invoke-BusBuddyPipelineChain',
        'Get-BusBuddySafeProperty',
        'ConvertTo-BusBuddyJson',
        'Format-BusBuddyString',
        'Get-BusBuddyPerformanceMetrics',
        'Test-BusBuddyHyperthreading',
        'Optimize-BusBuddyParallelism',
        'Set-BusBuddyPerformanceProfile'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = @(
        'BusBuddyPhysicalCores',
        'BusBuddyLogicalCores', 
        'BusBuddyMemoryGB',
        'BusBuddyHyperthreadRatio',
        'BusBuddyOptimalJobs'
    )

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @(
        'parallel',
        'fileproc',
        'pipechain', 
        'safeprop',
        'tojson',
        'fmtstr',
        'perfmetrics',
        'htinfo',
        'meminfo',
        'procinfo',
        'sysinfo',
        'httest',
        'htopt',
        'perfprof'
    )

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @(
                'BusBuddy',
                'PowerShell',
                'Performance',
                'Parallel',
                'Hyperthreading',
                'Development',
                'Azure',
                'Syncfusion',
                'WPF',
                'DotNet',
                'Threading',
                'Optimization'
            )

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/BusBuddy/PowerShell/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/BusBuddy/PowerShell'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = @'
## BusBuddy Advanced PowerShell Module v3.0.0

### New Features
- PowerShell 7.5.2 hyperthreading optimization
- Advanced parallel processing with machine-specific tuning
- Enhanced memory management and batch processing
- State-of-the-art pipeline chain operators
- Null-conditional operators and ternary support
- Performance monitoring with hyperthreading metrics
- Machine-specific environment variable configuration
- Advanced JSON processing with depth optimization
- Memory-efficient string interpolation

### Performance Improvements
- Automatic detection of physical/logical cores
- Optimized thread pool management
- Intelligent batch sizing based on system capabilities
- Memory threshold monitoring and management
- GC optimization for large datasets

### PowerShell 7.5.2 Features
- Experimental feature enablement
- Enhanced PSReadLine configuration
- Advanced key bindings and terminal persistence
- Improved error handling and logging
- Structured output streams compliance

### Environment Variables
- Comprehensive BusBuddy application configuration
- Machine-specific performance tuning
- Azure and cloud service integration
- Syncfusion UI framework optimization
- Database and security configuration
- Build and deployment automation
'@

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
