using System;
using System.Windows.Controls;
using BusBuddy.WPF.ViewModels;
using BusBuddy.Core.Data;
using Microsoft.EntityFrameworkCore;

namespace BusBuddy.WPF.Views
{
    /// <summary>
    /// Phase 2 Enhanced Drivers View - Temporary context creation for Phase 2
    /// </summary>
    public partial class DriversView : UserControl, IDisposable
    {
        private BusBuddyDbContext? _context;
        private bool _disposed;

        public DriversView()
        {
            // InitializeComponent will be auto-generated by XAML compiler

            // Phase 2: Create context with proper options (temporary solution)
            var options = new DbContextOptionsBuilder<BusBuddyDbContext>()
                .UseSqlite("Data Source=BusBuddy.db")
                .Options;

            _context = new BusBuddyDbContext(options);
            var viewModel = new DriversViewModel(_context);
            DataContext = viewModel;

            // Load data when view is created
            _ = viewModel.LoadDriversAsync();

            // Handle cleanup when view is unloaded
            Unloaded += (s, e) => Dispose();
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        protected virtual void Dispose(bool disposing)
        {
            if (!_disposed && disposing)
            {
                _context?.Dispose();
                _context = null;
                _disposed = true;
            }
        }
    }
}
