using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Controls;
using BusBuddy.Core.Mapping;
using BusBuddy.WPF.ViewModels.Map;
using Serilog;
using Serilog.Context;
using Syncfusion.UI.Xaml.Maps; // Official SfMap API reference: https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Maps.html
using Microsoft.Extensions.DependencyInjection;
using BusBuddy.Core.Data;
using System.Windows; // For Point, Size
using System.Printing; // Microsoft printing APIs
using System.Windows.Media; // Visual tree for printing
using System.Windows.Documents; // FixedDocument for printing
using System.Windows.Markup; // IAddChild
using Syncfusion.SfSkinManager;
using System.Windows.Media.Imaging; // For RenderTargetBitmap
using System.IO; // For MemoryStream / PNG encoder

namespace BusBuddy.WPF.Views.Map
{
    /// <summary>
    /// Interaction logic for MapView.xaml
    /// district map for advanced geospatial mapping and route visualization
    /// Enhanced with debounced layer changes and optimized background processing
    /// </summary>
    public partial class MapView : UserControl, IDisposable
    {
        private static readonly ILogger Logger = Log.ForContext<MapView>();
        // Safe accessor for the SfMap control declared as x:Name="GeoMap" in XAML
        // Using a property avoids compile-time issues if the generated field isn't available to analyzers
        private SfMap? MapControl => this.FindName("GeoMap") as SfMap;

        // Debouncing for map layer changes — avoids rapid layer swaps causing redundant work
        private readonly Timer _layerChangeDebounceTimer;
        private string? _pendingLayerType;
        private readonly object _layerChangeLock = new object();
        private const int LayerChangeDebounceDelayMs = 500;
        private bool _disposed;

        private MapViewModel? _boundViewModel;
        private MapLayer? _currentLayer; // Tracks current map layer
                                         // Cache of MapLayer instances by type to reduce allocations and tile re-fetches
        private readonly Dictionary<string, MapLayer> _layerCache = new(StringComparer.OrdinalIgnoreCase);

        // Sub-layer for drawing dynamic polylines on top of base imagery per Syncfusion docs (MapPolyline inside SubShapeFileLayer)
        private SubShapeFileLayer? _routeSubLayer;
        private MapPolyline? _routePolyline;

        // Reference to the Syncfusion SfMap control is generated by XAML as a field named 'GeoMap'.
        // Use that generated field directly to avoid duplicate member conflicts.

        public MapView()
        {
            using (LogContext.PushProperty("ViewInitialization", "MapView"))
            using (LogContext.PushProperty("PerformanceOptimizations", "Enabled"))
            {
                InitializeComponent();

                // Apply Syncfusion theme (FluentDark default, FluentLight fallback)
                ApplySyncfusionTheme();

                // Ensure DataContext is available — resolve from DI container when possible
                try
                {
                    if (DataContext is null && BusBuddy.WPF.App.ServiceProvider is not null)
                    {
                        var vmFromDi = BusBuddy.WPF.App.ServiceProvider.GetService<MapViewModel>();
                        if (vmFromDi is not null)
                        {
                            DataContext = vmFromDi;
                            Logger.Debug("MapViewModel resolved from DI and set as DataContext");
                        }
                    }
                }
                catch (Exception ex)
                {
                    Logger.Warning(ex, "Failed to resolve MapViewModel from DI");
                }

                // Initialize debounce timer for layer changes (UI events funnel to delayed apply)
                _layerChangeDebounceTimer = new Timer(OnLayerChangeDebounceElapsed, null, Timeout.Infinite, Timeout.Infinite);

                // Subscribe to Unloaded event for cleanup
                this.Unloaded += MapView_Unloaded;

                Logger.Information("map view initialized successfully with performance optimizations");
                Logger.Debug("Layer change debouncing configured with {DelayMs}ms delay", LayerChangeDebounceDelayMs);

                // Pre-warm layers to reduce first-switch latency
                PrewarmLayers();

                // Initialize map with default layer
                InitializeMapLayer("OpenStreetMap");
                TryResetView();

                // Kick off background health checks (DB connectivity, etc.)
                _ = Task.Run(CheckBackendConnectivityAsync);
            }
        }

        /// <summary>
        /// Ensure Syncfusion theme is applied consistently.
        /// Pattern mirrors FuelReconciliationDialog and follows Syncfusion SfSkinManager docs.
        /// </summary>
        private void ApplySyncfusionTheme()
        {
            BusBuddy.WPF.Utilities.SyncfusionThemeManager.ApplyTheme(this);
        }

        // Unloaded/Dispose implemented later in file with full dispose pattern

        /// <summary>
        /// Handles map layer SelectionChanged from ComboBoxAdv with debouncing to prevent rapid API calls.
        /// Sender is expected to be Syncfusion ComboBoxAdv with ComboBoxItemAdv items.
        /// </summary>
        private void MapLayerComboBox_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            var correlationId = Guid.NewGuid().ToString("N")[..8];

            using (LogContext.PushProperty("UserInteraction", "MapLayerChange"))
            using (LogContext.PushProperty("CorrelationId", correlationId))
            {
                try
                {
                    if (DataContext is not MapViewModel viewModel)
                    {
                        Logger.Warning("ViewModel not available for layer change operation");
                        return;
                    }

                    // ComboBoxAdv from Syncfusion raises SelectionChanged; validate sender and selected item types
                    if (sender is not Syncfusion.Windows.Tools.Controls.ComboBoxAdv comboBox ||
                        comboBox.SelectedItem is not Syncfusion.Windows.Tools.Controls.ComboBoxItemAdv selectedItem)
                    {
                        Logger.Debug("No valid selection detected in layer combo box");
                        return;
                    }

                    var layerType = selectedItem.Content?.ToString();
                    if (string.IsNullOrEmpty(layerType))
                    {
                        Logger.Warning("Selected layer type is null or empty");
                        return;
                    }

                    Logger.Debug("Layer change request received: {LayerType} (will be debounced)", layerType);

                    // Store the pending layer type and restart the debounce timer
                    lock (_layerChangeLock)
                    {
                        _pendingLayerType = layerType;
                        _layerChangeDebounceTimer.Change(LayerChangeDebounceDelayMs, Timeout.Infinite);
                    }
                }
                catch (Exception ex)
                {
                    Logger.Error(ex, "Failed to process layer change request: {ErrorMessage} (CorrelationId: {CorrelationId})",
                               ex.Message, correlationId);

                    // Could add user notification here if needed
                    // ShowUserFriendlyError("Failed to change map layer. Please try again.");
                }
            }
        }

        /// <summary>
        /// Applies pending layer change after debounce delay on a background thread, then marshals to UI thread.
        /// </summary>
        private async void OnLayerChangeDebounceElapsed(object? state)
        {
            string? layerTypeToApply;

            // Get the pending layer type safely
            lock (_layerChangeLock)
            {
                layerTypeToApply = _pendingLayerType;
                _pendingLayerType = null;
            }

            if (string.IsNullOrEmpty(layerTypeToApply))
            {
                return;
            }


            var correlationId = Guid.NewGuid().ToString("N")[..8];

            using (LogContext.PushProperty("BackgroundOperation", "DebouncedLayerChange"))
            using (LogContext.PushProperty("CorrelationId", correlationId))
            using (LogContext.PushProperty("LayerType", layerTypeToApply))
            {
                var stopwatch = System.Diagnostics.Stopwatch.StartNew();

                try
                {
                    Logger.Information("Executing debounced layer change to: {LayerType}", layerTypeToApply);

                    // Execute on UI thread — map layer updates must run on UI thread
                    await Dispatcher.InvokeAsync(() =>
                    {
                        using (LogContext.PushProperty("ThreadType", "UI"))
                        {
                            Logger.Debug("Applying geospatial layer change on UI thread");
                            InitializeMapLayer(layerTypeToApply!);
                        }
                    });

                    stopwatch.Stop();
                    Logger.Information("Layer change completed successfully in {ElapsedMs}ms", stopwatch.ElapsedMilliseconds);
                }
                catch (Exception ex)
                {
                    stopwatch.Stop();
                    Logger.Error(ex, "Failed to execute debounced layer change: {ErrorMessage} (Elapsed: {ElapsedMs}ms)",
                               ex.Message, stopwatch.ElapsedMilliseconds);
                }
            }
        }

        // Creates and applies a layer to SfMap per Syncfusion Maps docs
        private void InitializeMapLayer(string layerType)
        {
            try
            {
                using (LogContext.PushProperty("ApplyLayer", layerType))
                {
                    if (MapControl is null)
                    {
                        Logger.Warning("SfMap control not found in view");
                        return;
                    }

                    // Replace only the base imagery layer
                    RemoveBaseImageryLayer();
                    var newLayer = GetOrCreateLayer(layerType);

                    MapControl.Layers.Add(newLayer);
                    _currentLayer = newLayer;
                    Logger.Information("Applied map layer: {Layer}", layerType);

                    ToggleOsmAttribution(string.Equals(layerType, "OpenStreetMap", StringComparison.OrdinalIgnoreCase));

                    if (newLayer is ImageryLayer imagery)
                    {
                        ConfigureImageryLayer(imagery, DataContext as MapViewModel);
                    }
                }
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "Failed to initialize map layer: {LayerType}", layerType);
            }
        }

        // Remove only the current base imagery layer from GeoMap.Layers
        private void RemoveBaseImageryLayer()
        {
            try
            {
                if (MapControl is null)
                {
                    return;
                }
                if (_currentLayer is not null && MapControl.Layers.Contains(_currentLayer))
                {
                    MapControl.Layers.Remove(_currentLayer);
                    _currentLayer = null;
                }
            }
            catch (Exception ex)
            {
                Logger.Warning(ex, "Failed to remove base imagery layer");
            }
        }

        // Returns a cached layer or creates and caches one for reuse; avoids repeated allocations and CA2000 concerns
        private MapLayer GetOrCreateLayer(string layerType)
        {
            if (_layerCache.TryGetValue(layerType, out var existing))
            {
                return existing;
            }

            MapLayer created = new ImageryLayer { LayerType = LayerType.OSM };
            _layerCache["OpenStreetMap"] = created;
            return created;
        }

        // Pre-create commonly used layers to improve first-use responsiveness
        private void PrewarmLayers()
        {
            try
            {
                GetOrCreateLayer("OpenStreetMap");
                Logger.Debug("Pre-warmed map layers cache");
            }
            catch (Exception ex)
            {
                Logger.Warning(ex, "Error while pre-warming map layers");
            }
        }

        // Shows or hides the OSM attribution overlay based on active provider
        private void ToggleOsmAttribution(bool visible)
        {
            try
            {
                var overlay = this.FindName("OsmAttribution") as System.Windows.Controls.Border;
                if (overlay is not null)
                {
                    overlay.Visibility = visible ? System.Windows.Visibility.Visible : System.Windows.Visibility.Collapsed;
                }
            }
            catch (Exception ex)
            {
                Logger.Warning(ex, "Failed to toggle OSM attribution overlay");
            }
        }

        // Simple helpers for map view manipulation
        private void ConfigureImageryLayer(ImageryLayer imagery, MapViewModel? vm)
        {
            imagery.Center = new Point(MapDefaults.FallbackLatitude, MapDefaults.FallbackLongitude);
            if (vm is not null)
            {
                imagery.Markers = vm.MapMarkers;
                if (TryFindResource("StudentMarkerTemplate") is DataTemplate template)
                {
                    imagery.MarkerTemplate = template;
                }
            }

            if (_routeSubLayer is not null && !imagery.SubShapeFileLayers.Contains(_routeSubLayer))
            {
                imagery.SubShapeFileLayers.Add(_routeSubLayer);
            }
        }

        private void ApplyCenter(double latitude, double longitude, int? zoomLevel = null)
        {
            if (MapControl is null)
            {
                return;
            }

            if (zoomLevel.HasValue)
            {
                MapControl.ZoomLevel = zoomLevel.Value;
            }

            if (_currentLayer is ImageryLayer imagery)
            {
                imagery.Center = new Point(latitude, longitude);
            }
        }

        private void TryResetView()
        {
            try
            {
                ApplyCenter(MapDefaults.FallbackLatitude, MapDefaults.FallbackLongitude, MapDefaults.DefaultZoomLevel);
            }
            catch (Exception ex)
            {
                Logger.Warning(ex, "Failed to reset map view");
            }
        }

        // Basic backend connectivity check — verifies DbContext can connect if registered
        private async Task CheckBackendConnectivityAsync()
        {
            try
            {
                var sp = BusBuddy.WPF.App.ServiceProvider;
                if (sp is null)
                {
                    Logger.Debug("ServiceProvider not initialized — skipping backend connectivity check");
                    return;
                }

                using var scope = sp.CreateScope();
                var contextFactory = scope.ServiceProvider.GetService<IBusBuddyDbContextFactory>();
                if (contextFactory is null)
                {
                    Logger.Debug("IBusBuddyDbContextFactory not available — skipping DB connectivity check");
                    return;
                }

                using var context = contextFactory.CreateDbContext();
                var canConnect = await context.Database.CanConnectAsync();
                Logger.Information("Database connectivity check from MapView: {CanConnect}", canConnect);
            }
            catch (Exception ex)
            {
                Logger.Warning(ex, "Backend connectivity check failed");
            }
        }

        /// <summary>
        /// Handles DataContext changes to wire up ViewModel events — validates types and initializes background work.
        /// </summary>
        private void OnDataContextChanged(object sender, System.Windows.DependencyPropertyChangedEventArgs e)
        {
            var correlationId = Guid.NewGuid().ToString("N")[..8];

            using (LogContext.PushProperty("ViewModelBinding", "MapViewModel"))
            using (LogContext.PushProperty("CorrelationId", correlationId))
            {
                try
                {
                    // Cleanup old ViewModel if needed
                    if (e.OldValue is MapViewModel oldViewModel)
                    {
                        Logger.Debug("Cleaning up previous ViewModel binding");
                        DetachViewModel(oldViewModel);
                    }

                    if (e.NewValue is MapViewModel newViewModel)
                    {
                        Logger.Information("map view model connected successfully");
                        _boundViewModel = newViewModel;
                        newViewModel.ZoomInRequested += OnZoomInRequested;
                        newViewModel.ZoomOutRequested += OnZoomOutRequested;
                        newViewModel.CenterRequested += OnCenterRequested;
                        newViewModel.ViewResetRequested += OnViewResetRequested;
                        newViewModel.RouteLineUpdated += OnRouteLineUpdated;
                        newViewModel.PrintRequested += OnPrintRequested;
                    }
                    else if (e.NewValue != null)
                    {
                        Logger.Warning("DataContext is not of expected MapViewModel type: {ActualType}",
                                     e.NewValue.GetType().Name);
                    }
                    else
                    {
                        DetachViewModel(_boundViewModel);
                        _boundViewModel = null;
                        Logger.Debug("DataContext set to null");
                    }
                }
                catch (Exception ex)
                {
                    Logger.Error(ex, "Failed to handle DataContext change: {ErrorMessage}", ex.Message);
                }
            }
        }

        private void DetachViewModel(MapViewModel? viewModel)
        {
            if (viewModel is null)
            {
                return;
            }

            try
            {
                viewModel.RouteLineUpdated -= OnRouteLineUpdated;
                viewModel.PrintRequested -= OnPrintRequested;
                viewModel.ZoomInRequested -= OnZoomInRequested;
                viewModel.ZoomOutRequested -= OnZoomOutRequested;
                viewModel.CenterRequested -= OnCenterRequested;
                viewModel.ViewResetRequested -= OnViewResetRequested;
            }
            catch (Exception ex)
            {
                Logger.Warning(ex, "Error while detaching from MapViewModel events");
            }
        }

        private void OnRouteLineUpdated(object? sender, MapViewModel.RouteLineEventArgs e)
        {
            try
            {
                if (MapControl is null)
                {
                    return;
                }

                // Ensure sub-layer and polyline exist
                if (_routeSubLayer is null)
                {
                    _routeSubLayer = new SubShapeFileLayer();
                    if (_currentLayer is ImageryLayer imagery)
                    {
                        imagery.SubShapeFileLayers.Add(_routeSubLayer);
                    }
                    else
                    {
                        // Fallback: add as top-level layer if imagery unavailable
                        MapControl.Layers.Add(_routeSubLayer);
                    }
                }
                if (_routePolyline is null)
                {
                    _routePolyline = new MapPolyline
                    {
                        Stroke = System.Windows.Media.Brushes.Gold,
                        StrokeThickness = 3
                    };
                    _routeSubLayer.MapElements.Add(_routePolyline);
                }

                // Replace points
                _routePolyline.Points = new System.Collections.ObjectModel.ObservableCollection<Point>(e.Points);
            }
            catch (Exception ex)
            {
                Logger.Warning(ex, "Failed updating route polyline");
            }
        }

        private void OnPrintRequested(object? sender, EventArgs e)
        {
            try
            {
                if (MapControl is null)
                {
                    return;
                }

                if (MapControl is not System.Windows.FrameworkElement mapElement)
                {
                    return;
                }

                var printDlg = new System.Windows.Controls.PrintDialog();
                if (printDlg.ShowDialog() != true)
                {
                    return;
                }

                var doc = new FixedDocument();
                doc.DocumentPaginator.PageSize = new Size(printDlg.PrintableAreaWidth, printDlg.PrintableAreaHeight);

                var pageContent = new PageContent();
                var fixedPage = new FixedPage
                {
                    Width = printDlg.PrintableAreaWidth,
                    Height = printDlg.PrintableAreaHeight
                };

                var rect = new System.Windows.Shapes.Rectangle
                {
                    Width = fixedPage.Width,
                    Height = fixedPage.Height * 0.8,
                    Fill = new VisualBrush(mapElement)
                };
                FixedPage.SetLeft(rect, 0);
                FixedPage.SetTop(rect, 0);
                fixedPage.Children.Add(rect);

                var caption = new System.Windows.Controls.TextBlock
                {
                    Text = "Route map printout",
                    Margin = new Thickness(24, fixedPage.Height * 0.82, 24, 24),
                    FontSize = 16
                };
                fixedPage.Children.Add(caption);

                ((IAddChild)pageContent).AddChild(fixedPage);
                doc.Pages.Add(pageContent);

                printDlg.PrintDocument(doc.DocumentPaginator, "BusBuddy Route Map");

                // New: Use ViewModel snapshot helper for consistency
                if (DataContext is MapViewModel vm)
                {
                    vm.CaptureMapSnapshot(mapElement);
                }
            }
            catch (Exception ex)
            {
                Logger.Warning(ex, "Failed to print route map");
            }
        }

        /// <summary>
        /// Captures a PNG snapshot of the current map visual and stores it in the ViewModel's LatestMapSnapshotPng.
        /// Uses RenderTargetBitmap (Microsoft WPF imaging docs) and PngBitmapEncoder (official .NET imaging API).
        /// </summary>
        private void TryCaptureMapSnapshot()
        {
            try
            {
                if (MapControl is not FrameworkElement mapElement)
                {
                    return;
                }
                if (DataContext is not MapViewModel vm)
                {
                    return;
                }

                var width = (int)Math.Ceiling(mapElement.ActualWidth);
                var height = (int)Math.Ceiling(mapElement.ActualHeight);
                if (width <= 0 || height <= 0)
                {
                    return;
                }

                // Render at 96 DPI (standard) — can be increased later for higher resolution
                var rtb = new RenderTargetBitmap(width, height, 96, 96, PixelFormats.Pbgra32);
                rtb.Render(mapElement);

                var encoder = new PngBitmapEncoder();
                encoder.Frames.Add(BitmapFrame.Create(rtb));
                using var ms = new MemoryStream();
                encoder.Save(ms);
                vm.LatestMapSnapshotPng = ms.ToArray();
                Logger.Information("Captured map snapshot PNG ({Bytes} bytes) for PDF embedding", vm.LatestMapSnapshotPng.Length);
            }
            catch (Exception ex)
            {
                Logger.Warning(ex, "Map snapshot capture failed");
            }
        }


        /// <summary>
        /// OnInitialized — subscribes to DataContextChanged and completes view initialization.
        /// </summary>
        protected override void OnInitialized(EventArgs e)
        {
            using (LogContext.PushProperty("ViewLifecycle", "Initialization"))
            {
                try
                {
                    base.OnInitialized(e);
                    DataContextChanged += OnDataContextChanged;

                    Logger.Debug("MapView initialization completed successfully");
                }
                catch (Exception ex)
                {
                    Logger.Error(ex, "Failed during MapView initialization");
                    throw; // Re-throw to allow proper error handling upstream
                }
            }
        }

        /// <summary>
        /// Cleanup resources when the view is being disposed
        /// </summary>
        private void MapView_Unloaded(object sender, System.Windows.RoutedEventArgs e)
        {
            using (LogContext.PushProperty("ViewLifecycle", "Unloaded"))
            {
                Logger.Debug("MapView unloaded, disposing resources");
                Dispose();
            }
        }

        /// <summary>
        /// Dispose pattern implementation
        /// </summary>
        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        /// <summary>
        /// Protected dispose method
        /// </summary>
        protected virtual void Dispose(bool disposing)
        {
            if (!_disposed && disposing)
            {
                try
                {
                    _layerChangeDebounceTimer?.Dispose();
                    DetachViewModel(_boundViewModel);
                    _boundViewModel = null;
                    DataContextChanged -= OnDataContextChanged;
                    this.Unloaded -= MapView_Unloaded;
                    try
                    {
                        // Dispose Syncfusion skin resources
                        SfSkinManager.Dispose(this);
                    }
                    catch (Exception ex)
                    {
                        Logger.Warning(ex, "Failed to dispose SfSkinManager resources for {ViewName}", GetType().Name);
                    }
                    try
                    {
                        // Clear map layers and dispose cached layers
                        if (MapControl is not null)
                        {
                            MapControl.Layers.Clear();
                        }
                        foreach (var layer in _layerCache.Values)
                        {
                            (layer as IDisposable)?.Dispose();
                        }
                        _layerCache.Clear();
                    }
                    catch (Exception ex)
                    {
                        Logger.Warning(ex, "Error while disposing cached map layers");
                    }
                    Logger.Debug("MapView resources disposed successfully");
                }
                catch (Exception ex)
                {
                    Logger.Error(ex, "Error during MapView disposal");
                }
                finally
                {
                    _disposed = true;
                }
            }
        }

        private void ApplyZoom(int delta)
        {
            try
            {
                if (MapControl is null) return;
                var current = MapControl.ZoomLevel; // documented property on SfMap
                var target = current + delta;
                if (target < 1) target = 1;
                if (target > 18) target = 18; // practical upper bound for tile providers
                MapControl.ZoomLevel = target;
                Logger.Debug("Map zoom changed from {Old} to {New}", current, target);
            }
            catch (Exception ex)
            {
                Logger.Warning(ex, "ApplyZoom failed");
            }
        }

        private void OnZoomInRequested(object? sender, EventArgs e) => Dispatcher.Invoke(() => ApplyZoom(+1));
        private void OnZoomOutRequested(object? sender, EventArgs e) => Dispatcher.Invoke(() => ApplyZoom(-1));
        private void OnCenterRequested(object? sender, EventArgs e) => Dispatcher.Invoke(CenterOnCurrentMarkers);
        private void OnViewResetRequested(object? sender, EventArgs e) => Dispatcher.Invoke(TryResetView);

        private void CenterOnCurrentMarkers()
        {
            try
            {
                if (MapControl is null) return;
                if (DataContext is not MapViewModel vm) return;
                if (vm.MapMarkers.Count == 0) return;
                double minLat = double.MaxValue, maxLat = double.MinValue, minLon = double.MaxValue, maxLon = double.MinValue;
                foreach (var mk in vm.MapMarkers)
                {
                    if (mk.LatitudeDegrees < minLat) minLat = mk.LatitudeDegrees;
                    if (mk.LatitudeDegrees > maxLat) maxLat = mk.LatitudeDegrees;
                    if (mk.LongitudeDegrees < minLon) minLon = mk.LongitudeDegrees;
                    if (mk.LongitudeDegrees > maxLon) maxLon = mk.LongitudeDegrees;
                }
                var centerLat = (minLat + maxLat) / 2d;
                var centerLon = (minLon + maxLon) / 2d;
                ApplyCenter(centerLat, centerLon, MapDefaults.DefaultZoomLevel);
                Logger.Debug("Centered map on marker centroid {Lat},{Lon}", centerLat, centerLon);
            }
            catch (Exception ex)
            {
                Logger.Warning(ex, "CenterOnCurrentMarkers failed");
            }
        }
    }
}
